// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RGBA represents a traditional 32-bit alpha-premultiplied color, having 8
 * bits for each of red, green, blue and alpha.
 * 
 * An alpha-premultiplied color component C has been scaled by alpha (A), so
 * has valid values 0 <= C <= A.
 */
export interface RGBA {
    "R": number;
    "G": number;
    "B": number;
    "A": number;
}
