allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@wailsio/runtime@3.0.0-beta.17 || 3.0.0-beta.19'
  - jscpd-darwin-arm64@5.2.1
  - jscpd-darwin-x64@5.2.1
  - jscpd-linux-arm64-gnu@5.2.1
  - jscpd-linux-arm64-musl@5.2.1
  - jscpd-linux-x64-gnu@5.2.1
  - jscpd-linux-x64-musl@5.2.1
  - jscpd-windows-arm64-msvc@5.2.1
  - jscpd-windows-x64-msvc@5.2.1
  - jscpd@5.2.1
  - '@typescript-eslint/eslint-plugin@8.71.0'
  - '@typescript-eslint/parser@8.71.0'
  - '@typescript-eslint/project-service@8.71.0'
  - '@typescript-eslint/scope-manager@8.71.0'
  - '@typescript-eslint/tsconfig-utils@8.71.0'
  - '@typescript-eslint/type-utils@8.71.0'
  - '@typescript-eslint/types@8.71.0'
  - '@typescript-eslint/typescript-estree@8.71.0'
  - '@typescript-eslint/utils@8.71.0'
  - '@typescript-eslint/visitor-keys@8.71.0'
  - typescript-eslint@8.71.0
  - eslint@10.12.0
