// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as domain$0 from "../../../../../soteria/internal/domain/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "dragend": boolean;
            "dropped": string[] | null;
            "index": domain$0.IndexStatus;
            "nav": string;
            "transfer": domain$0.Transfer;
        }
    }
}
