// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Conflict {
    "local": string;
    "remote": string;
    "dir": boolean;
    "size": number;
    "modified": string;
    "localSize": number;
    "localModified": string;
}

export interface Drive {
    "path": string;
    "mounted": boolean;
}

export interface Entry {
    "name": string;
    "path": string;
    "dir": boolean;
    "size": number;
    "modified": string;
    "created": string;
    "contentType": string;
    "etag": string;
}

export interface IndexStatus {
    "count": number;
    "folders": number;
    "pending": number;
    "done": boolean;
    "at": number;
}

/**
 * Quota in bytes; -1 when the server does not report it.
 */
export interface Quota {
    "used": number;
    "available": number;
}

export interface Server {
    "id": string;
    "name": string;
    "url": string;
    "username": string;
    "insecure": boolean;
    "remember": boolean;
    "lastUsed": number;
}

export interface Transfer {
    "id": string;
    "kind": string;
    "group": string;
    "name": string;
    "remote": string;
    "local": string;
    "done": number;
    "total": number;
    "status": string;
    "error": string;
}

export interface TrashItem {
    "name": string;
    "path": string;
    "dir": boolean;
    "size": number;
    "modified": string;
    "created": string;
    "contentType": string;
    "etag": string;
    "from": string;
    "deleted": string;
}

export interface Update {
    "current": string;
    "state": string;
    "blocked": boolean;
    "version": string;
    "notes": string;
    "size": number;
    "date": string;
    "url": string;
}

export interface Usage {
    "known": boolean;
    "items": number;
    "bytes": number;
}
