// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as color$0 from "../../../../../../../image/color/models.js";

/**
 * BadgeOptions represents options for customizing badge appearance
 */
export interface BadgeOptions {
    "TextColour": color$0.RGBA;
    "BackgroundColour": color$0.RGBA;
    "FontName": string;
    "FontSize": number;
    "SmallFontSize": number;
}
