// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationAction represents an action button for a notification.
 */
export interface NotificationAction {
    "id"?: string;
    "title"?: string;

    /**
     * (macOS-specific)
     */
    "destructive"?: boolean;
}

/**
 * NotificationAttachment is a media file shown with the notification.
 * Path is an absolute filesystem path (or "file://" URL on macOS).
 */
export interface NotificationAttachment {
    "id"?: string;
    "path": string;

    /**
     * Type is an optional placement/UTI hint.
     *   On macOS: a UTI like "public.png" / "public.audio" (often inferred).
     *   On Windows: "hero" | "appLogoOverride" | "inline" (default "inline").
     *   On Linux: ignored (always image-path hint).
     */
    "type"?: string;
}

/**
 * NotificationCategory groups actions for notifications.
 */
export interface NotificationCategory {
    "id"?: string;
    "actions"?: NotificationAction[] | null;
    "hasReplyField"?: boolean;
    "replyPlaceholder"?: string;
    "replyButtonTitle"?: string;
}

/**
 * NotificationOptions contains configuration for a notification.
 * 
 * New optional fields (Sound, Attachments, ThreadID, InterruptionLevel,
 * Schedule) gracefully degrade when a platform cannot honour them; see the
 * package-level godoc for the per-platform support matrix.
 */
export interface NotificationOptions {
    "id": string;
    "title": string;

    /**
     * (macOS and Linux only)
     */
    "subtitle"?: string;
    "body"?: string;
    "categoryId"?: string;
    "data"?: { [_ in string]?: any } | null;

    /**
     * Sound controls the sound played on delivery.
     *   nil                                -> platform default sound
     *   &NotificationSound{Silent: true}   -> no sound
     *   &NotificationSound{Name: "Ping"}   -> named/bundled sound
     * On macOS, Name is resolved by [UNNotificationSound soundNamed:] and
     * requires the audio file to live under the bundle's Library/Sounds.
     * On Windows, Name is used as-is if it begins with "ms-winsoundevent:" or
     * "ms-appx:"; otherwise it is wrapped in "ms-winsoundevent:" for built-in
     * event names. On Linux it is forwarded as the freedesktop "sound-name"
     * hint (theme-dependent).
     */
    "sound"?: NotificationSound | null;

    /**
     * Attachments are media files shown alongside the notification. macOS
     * supports multiple attachments of any media type; Windows and Linux
     * honour the first image-typed attachment (Linux limits to one per spec).
     */
    "attachments"?: NotificationAttachment[] | null;

    /**
     * ThreadID groups related notifications together in Notification Center
     * (macOS) / Action Center (Windows) / the notification daemon (Linux).
     */
    "threadId"?: string;

    /**
     * InterruptionLevel controls notification priority. One of "passive",
     * "active" (default), "timeSensitive", "critical". Critical requires
     * macOS 12+ and the Critical Alert entitlement. Linux maps to the
     * freedesktop urgency hint; Windows maps to <toast scenario="...">.
     */
    "interruptionLevel"?: string;

    /**
     * Schedule defers delivery. macOS uses a native trigger and persists
     * across app restarts. Windows and Linux fall back to an in-process
     * time.AfterFunc timer that does NOT survive an app exit.
     */
    "schedule"?: NotificationSchedule | null;
}

/**
 * NotificationSchedule defers delivery. Exactly one of DelaySeconds or At
 * must be set. At is interpreted as Unix seconds (UTC).
 */
export interface NotificationSchedule {
    "delaySeconds"?: number;
    "at"?: number;
}

/**
 * NotificationSound configures audio playback for a notification.
 */
export interface NotificationSound {
    "silent"?: boolean;
    "name"?: string;
}
