// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(606781307, id);
}

export function CancelGroup(group: string): $CancellablePromise<void> {
    return $Call.ByID(3968580370, group);
}

export function CheckUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2442005206);
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(3733565954);
}

export function Connect(s: domain$0.Server, pw: string): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(1925521113, s, pw);
}

export function ConnectSaved(id: string): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(2865824184, id);
}

export function Copy($from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(3474208420, $from, to);
}

export function Current(): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(1217412538);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2705595211);
}

export function Download(remote: string, size: number, dest: string): $CancellablePromise<string> {
    return $Call.ByID(3510037337, remote, size, dest);
}

export function DownloadDir(remote: string, dest: string): $CancellablePromise<void> {
    return $Call.ByID(2884284968, remote, dest);
}

/**
 * DragOut starts a native drag of remote files; Finder asks for each file on drop and it is downloaded there.
 */
export function DragOut(entries: domain$0.Entry[] | null): $CancellablePromise<void> {
    return $Call.ByID(1122960181, entries);
}

/**
 * drive
 */
export function Drive(): $CancellablePromise<domain$0.Drive> {
    return $Call.ByID(2672827735);
}

export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(2922579444);
}

export function Forget(id: string): $CancellablePromise<void> {
    return $Call.ByID(3085677516, id);
}

export function Indexed(): $CancellablePromise<domain$0.IndexStatus> {
    return $Call.ByID(831317578);
}

export function InstallDriver(): $CancellablePromise<void> {
    return $Call.ByID(3190090398);
}

/**
 * InstallUpdate downloads and verifies in the background; progress arrives on the wails:updater:* events.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3404727425);
}

export function Link(p: string): $CancellablePromise<string> {
    return $Call.ByID(324235465, p);
}

/**
 * files
 */
export function List(p: string): $CancellablePromise<domain$0.Entry[] | null> {
    return $Call.ByID(309576417, p);
}

export function ListTrash(): $CancellablePromise<domain$0.TrashItem[] | null> {
    return $Call.ByID(3173583841);
}

export function LogPath(): $CancellablePromise<string> {
    return $Call.ByID(3961886186);
}

export function Mkdir(p: string): $CancellablePromise<void> {
    return $Call.ByID(347263160, p);
}

export function Mount(): $CancellablePromise<domain$0.Drive> {
    return $Call.ByID(3571799450);
}

export function Move($from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(74888564, $from, to);
}

export function Open(p: string): $CancellablePromise<void> {
    return $Call.ByID(3637980969, p);
}

export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(3351796252);
}

export function PickUploads(dir: string): $CancellablePromise<domain$0.Conflict[] | null> {
    return $Call.ByID(2372486830, dir);
}

export function Ping(): $CancellablePromise<void> {
    return $Call.ByID(42472169);
}

export function Purge(p: string): $CancellablePromise<void> {
    return $Call.ByID(3343183076, p);
}

export function Quota(): $CancellablePromise<domain$0.Quota> {
    return $Call.ByID(816059755);
}

export function Recent(n: number): $CancellablePromise<domain$0.Entry[] | null> {
    return $Call.ByID(2168970302, n);
}

/**
 * search
 */
export function Reindex(): $CancellablePromise<void> {
    return $Call.ByID(1654599532);
}

export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2853079796);
}

export function Restore(p: string): $CancellablePromise<void> {
    return $Call.ByID(3809830833, p);
}

export function Retry(id: string): $CancellablePromise<void> {
    return $Call.ByID(386499737, id);
}

export function Reveal(local: string): $CancellablePromise<void> {
    return $Call.ByID(3917975088, local);
}

export function Search(q: string): $CancellablePromise<domain$0.Entry[] | null> {
    return $Call.ByID(267664905, q);
}

/**
 * session
 */
export function Servers(): $CancellablePromise<domain$0.Server[] | null> {
    return $Call.ByID(2304319571);
}

/**
 * SetBackground mirrors the two Settings switches; the frontend calls it on start and on change.
 */
export function SetBackground(on: boolean, notify: boolean): $CancellablePromise<void> {
    return $Call.ByID(2323405311, on, notify);
}

export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(3454649544);
}

/**
 * transfers
 */
export function Transfers(): $CancellablePromise<domain$0.Transfer[] | null> {
    return $Call.ByID(377283727);
}

/**
 * trash
 */
export function Trash(p: string): $CancellablePromise<string> {
    return $Call.ByID(3766480357, p);
}

export function Unmount(): $CancellablePromise<void> {
    return $Call.ByID(3483254379);
}

export function UpdateStatus(): $CancellablePromise<domain$0.Update> {
    return $Call.ByID(1731050910);
}

export function Upload(locals: string[] | null, dir: string): $CancellablePromise<domain$0.Conflict[] | null> {
    return $Call.ByID(2958425276, locals, dir);
}

export function UploadAs(local: string, remote: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3268360156, local, remote, mode);
}
