// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Drop is a file drop: the local paths and, when they landed on a folder row, that folder.
 */
export interface Drop {
    "files": string[] | null;
    "dir": string;
}
